# group_vars/all.yml

mysql_root_password: "R00tP@ss!"
mysql_user_password: "UserP@ss!"
mysql_flag: "FLAG{mysql_secret_data_exposed}"
mongo_password: "MongoP@ss!"
mongo_flag: "FLAG{mongodb_no_auth_misconfiguration}"

# Ejabberd
ejabberd_admin_password: "Admin@1234"
ejabberd_db_password: "EjabberdDB@123"
ejabberd_db_name: "ejabberd"
ejabberd_db_user: "ejabberd"
ejabberd_flag: "FLAG{ejabberd_xmpp_misconfigured}"

# Contestant login for ALL machines
contestant_user: user
contestant_password: "Password123"

# Stack
stack_prefix: ""